export const ERROR_STATUS_BY_CODE: Record<string, number> = {
  INTERNAL_ERROR: 500,
  CONVEX_ERROR: 400,
  UNAUTHENTICATED: 401,
  DEVICE_UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  INACTIVE_USER: 403,
  USER_NOT_FOUND: 404,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 400,
  BAD_REQUEST: 400,
  ONBOARDING_REQUIRED: 409,
  WORKSPACE_ACCESS_LOST: 409,
  TOKEN_UNKNOWN: 400,
  TOKEN_EXPIRED: 400,
  TOKEN_REPLAY: 409,
  INVALID_TOKEN_FOR_DEVICE: 403,
  GEOFENCE_NOT_CONFIGURED: 503,
  GEOFENCE_COORD_REQUIRED: 400,
  GEOFENCE_ACCURACY_REQUIRED: 400,
  GEOFENCE_ACCURACY_TOO_LOW: 400,
  GEOFENCE_OUTSIDE_RADIUS: 403,
  IP_NOT_ALLOWED: 403,
  SPAM_DETECTED: 429,
  DEVICE_HEARTBEAT_STALE: 403,
  WRITE_CONFLICT: 409,
  PLAN_LIMIT_REACHED: 409,
  SETTINGS_NOT_INITIALIZED: 503,
  FEATURE_NOT_AVAILABLE: 403,
  WORKSPACE_REQUIRED: 400,
  WORKSPACE_INVALID: 400,
  WORKSPACE_PLAN_INVALID: 400,
  WORKSPACE_PLAN_LIMIT_KEY_INVALID: 400,
  WORKSPACE_PLAN_FEATURE_KEY_INVALID: 400,
  CODE_NOT_FOUND: 400,
  CODE_INACTIVE: 400,
  CODE_EXPIRED: 400,
  ALREADY_MEMBER: 409,
  INVITE_CODE_NOT_FOUND: 404,
  WORKSPACE_DELETE_BLOCKED: 409,
  REGISTRATION_CODE_INVALID: 400,
  REGISTRATION_CODE_REVOKED: 409,
  REGISTRATION_CODE_CLAIMED: 409,
  REGISTRATION_CODE_EXPIRED: 400,
};

export const CLIENT_MESSAGE_BY_CODE: Record<string, string> = {
  INTERNAL_ERROR: "Terjadi gangguan sistem. Coba lagi beberapa saat.",
  DEVICE_UNAUTHORIZED: "Sesi perangkat QR tidak valid. Silakan login ulang perangkat.",
  UNAUTHENTICATED: "Sesi login berakhir. Silakan login ulang.",
  FORBIDDEN: "Anda tidak memiliki izin untuk aksi ini.",
  USER_NOT_FOUND: "Data user tidak ditemukan. Silakan sinkronisasi ulang akun.",
  INACTIVE_USER: "Akun Anda tidak aktif. Hubungi superadmin.",
  VALIDATION_ERROR: "Input tidak valid. Periksa lagi data yang dimasukkan.",
  PLAN_LIMIT_REACHED: "Paket workspace Anda sudah mencapai batas penggunaan fitur ini.",
  FEATURE_NOT_AVAILABLE: "Fitur ini hanya tersedia pada paket workspace yang lebih tinggi.",
  WORKSPACE_PLAN_INVALID:
    "Paket workspace tidak valid. Hubungi tim support atau periksa data workspace.",
  WORKSPACE_REQUIRED: "Workspace aktif belum dipilih. Pilih workspace terlebih dahulu.",
  WORKSPACE_INVALID: "Workspace aktif tidak valid. Pilih ulang workspace Anda.",
  ONBOARDING_REQUIRED:
    "Anda belum tergabung di workspace aktif mana pun. Buat atau gabung ke workspace terlebih dahulu.",
  WORKSPACE_ACCESS_LOST:
    "Akses ke workspace aktif sudah berubah. Pilih ulang workspace yang masih tersedia.",
  BAD_REQUEST: "Permintaan tidak valid.",
  NOT_FOUND: "Data yang diminta tidak ditemukan.",
  WRITE_CONFLICT: "Terjadi konflik data. Silakan coba lagi.",
  SPAM_DETECTED: "Aksi terlalu cepat. Tunggu sebentar lalu coba lagi.",
  DEVICE_HEARTBEAT_STALE:
    "Perangkat QR sedang offline. Minta petugas menyegarkan perangkat QR.",
  INVITE_CODE_NOT_FOUND: "Invitation code aktif tidak ditemukan.",
  WORKSPACE_DELETE_BLOCKED:
    "Workspace belum bisa dihapus karena masih ada member aktif lain.",
  REGISTRATION_CODE_INVALID: "Kode registrasi tidak valid.",
  REGISTRATION_CODE_REVOKED: "Kode registrasi sudah tidak aktif.",
  REGISTRATION_CODE_CLAIMED: "Kode registrasi sudah dipakai.",
  REGISTRATION_CODE_EXPIRED: "Kode registrasi sudah kedaluwarsa.",
  GEOFENCE_NOT_CONFIGURED:
    "Area absensi kantor belum dikonfigurasi dengan benar. Hubungi admin workspace.",
  GEOFENCE_ACCURACY_REQUIRED:
    "Izin lokasi dan akurasi GPS diperlukan untuk scan di area kantor.",
  GEOFENCE_ACCURACY_TOO_LOW:
    "Akurasi GPS Anda belum cukup. Dekatkan diri ke area terbuka lalu coba lagi.",
};
